#  _
# | |   _   _ _ __ ___   ___ _ __
# | |  | | | | '_ ` _ \ / _ \ '_ \
# | |__| |_| | | | | | |  __/ | | |
# |_____\__,_|_| |_| |_|\___|_| |_|

language: "es_es" # Language of the plugin

settings:
  # Lumen Command settings
  command_lights_per_tick: 1000 # Quantity of lights added per tick with the command

  # Lumen Torch settings
  default_torch_radius: 20 # Radius of the torch
  torch_lights_per_tick: 10 # Quantity of lights added per tick with the torch
  torch_tick_interval: 10 # Interval between torch ticks

  # Lumen Mob Torch settings
  mob_torch_radius: 35 # Radius of the mob torch
  mob_torch_search_range: 100 # Range of the mob torch search