#  _
# | |   _   _ _ __ ___   ___ _ __
# | |  | | | | '_ ` _ \ / _ \ '_ \
# | |__| |_| | | | | | |  __/ | | |
# |_____\__,_|_| |_| |_|\___|_| |_|


# Support: https://soystargaze.com/discord
# Version: 1.1.0

# Plugin settings
# Language of the plugin
language: "en_us"
translations:
  force-update: true # Force update the translations (Recommended)

settings:
  update-check: true # Check for updates on admin join

  # Lumen Command settings
  command_lights_per_tick: 1000 # Quantity of lights added per tick with the command

  # Async settings
  async_thread_pool_size: 4 # Quantity of threads used for async tasks

  # Lumen Torch settings
  default_torch_radius: 20 # Radius of the torch
  torch_light_level: 15 # Light level of the torch 0-15
  torch_lights_per_tick: 10 # Quantity of lights added per tick with the torch
  torch_tick_interval: 10 # Interval between torch ticks

  # Lumen Mob Torch settings
  mob_torch_radius: 35 # Radius of the mob torch
  mob_torch_search_range: 100 # Range of the mob torch search

# Lumen Bossbar and Actionbar settings
display:
  bossbar:
    enabled: true
    message: "Progress: {progress}% completed"
    color: "YELLOW"
    style: "SOLID"
  actionbar:
    enabled: true
    message: "Progress: {progress}% completed"

# Lumen Torch and Guard items
items:
  torch:
    name: "<yellow>Lumen Torch</yellow>"
    lore: "<white>Place this torch to illuminate the area around it.</white> <gray>(Right-click to change intensity)</gray>"
  guard:
    name: "<blue>Lumen Guard</blue>"
    lore: "<white>Place this guard to protect the area against hostile mobs.</white>"