name: Lumen
version: '1.1.0'
main: com.soystargaze.lumen.Lumen
api-version: '1.21'
load: STARTUP
authors: [Eros Marí]
website: https://erosmari.com
softdepend:
  - CoreProtect
  - FastAsyncWorldEdit
ommands:
  lumen:
    description: Main command for Lumen
    usage: /<command> [subcommand] [...]
    aliases:
      - lu
      - l

permissions:
  lumen.use:
    description: Allows use of /lumen and all its subcommands
    default: op
  lumen.light:
    description: Allows placing light blocks
    default: op
  lumen.lang:
    description: Allows changing language
    default: op
  lumen.redo:
    description: Allows redoing light operations
    default: op
  lumen.give:
    description: Allows giving Lumen items
    default: op
  lumen.undo:
    description: Allows undoing light operations
    default: op
  lumen.remove:
    description: Allows removing light blocks
    default: op
  lumen.cancel:
    description: Allows canceling active tasks
    default: op
  lumen.reload:
    description: Allows reloading the configuration
    default: op
  lumen.clear:
    description: Allows clearing all light blocks
    default: op